version: '3.8'

services:
  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  ffmpeg-video-app:
    image: ffmpeg-video-app:latest
    container_name: ffmpeg-video-app
    depends_on:
      - redis
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    command: ['npm', 'start']

volumes:
  redis-data:
